# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "action_cost"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Philippe Le Rohellec"]
  s.date = "2013-03-24"
  s.description = "ActionCost measures the performance of a Rails 3 app controller actions in terms of number of calls to the database and to RecordCache."
  s.email = "philippe@lerohellec.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "action_cost.gemspec",
    "app/controllers/action_cost/dashboards_controller.rb",
    "app/views/action_cost/dashboards/ca.html.erb",
    "app/views/action_cost/dashboards/index.html.erb",
    "app/views/layouts/action_cost.html.erb",
    "config/routes.rb",
    "lib/action_cost.rb",
    "lib/action_cost/active_record/gauge.rb",
    "lib/action_cost/engine.rb",
    "lib/action_cost/extensions/postgresql_adapter.rb",
    "lib/action_cost/middleware.rb",
    "lib/action_cost/record_cache/index_hook.rb",
    "lib/action_cost/record_cache_parser.rb",
    "lib/action_cost/request_stats.rb",
    "lib/action_cost/sql_parser.rb",
    "lib/action_cost/stats_collector.rb",
    "test/helper.rb",
    "test/test_action_cost.rb"
  ]
  s.homepage = "http://github.com/plerohellec/action_cost"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "ActionCost measures the cost of controller action"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

